dist: xenial
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

cache:
  apt: true
  pip: true

addons:
  apt_packages:
    - sqlite3

env:
  matrix:
    - TOXENV="py27"
    - TOXENV="py35"
    - TOXENV="py36"
    - TOXENV="py37"

before_install: 
    - pip install --upgrade tox-travis pip virtualenv wheel setuptools --quiet
    - pyenv global system 2.7 3.5 3.6 3.7
before_script: pyclean --verbose .
script: tox

notifications:
    email:
        recipients: slinkymanbyday@gmail.com
        template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number},SHA: %{commit},Committer: %{author},Diff: %{compare_url}"
        on_success: always
        on_failure: always
